### ISSUE TITLE
Loading stops when installed.

### ISSUE THREAD

**Issue by BobTheKerbal** [TheProtagonists/TheWorldBeyond#3]
When I have the mod installed, during loading module manager stops completely and when I look at the Debug toolbar, its just a giant line of red and stuff about 'scatterer'
Output log: https://www.dropbox.com/s/ivemz9zxnro89ch/output_log.txt?dl=0
Any solution? _Thanks, Me._

**Comment by TheProtagonists** [comment]
Just based off how kopernicus parsed those configs it seems like you are not installing the mod correctly.
If you are installing TWB_Full, **_make sure you extract the download by using extract here and NOT extract to..._**, since it seems like you have put the TWB_Full folder into your GameData when you should have put the TheWorldBeyond folder in GameData instead.

**Comment by BobTheKerbal** [comment]
ok I will try that!

**Comment by BobTheKerbal** [comment]
Mono causes an access violation when I do what you said.

**Comment by TheProtagonists** [comment]
Access violations can happen randomly when you have too little memory left when you are loading the game or switching scenes. Can you load up the game again and see if the same thing happens? I see you are running on 64 bit, but how much RAM do you have? Because if you are using TWB and a lot of other mods you might be out of memory.

**Comment by BobTheKerbal** [comment]
Oh yeah, I have the OPM mod, Before Kerbin, Kopernicus expansion, Community terrain texture pack, Other worlds reboot, Extrasolar: Planets beyond kerbol, KargantuaSystem, EVE, Its a mess of planets everywhere.

**Comment by BobTheKerbal** [comment]
So I could see why.

**Comment by BobTheKerbal** [comment]
Let me try taking them out and trying just kopernicus and its expansion with TWB full.

**Comment by TheProtagonists** [comment]
If you are trying that make sure to still keep scatterer and EVE since TWB full has all the visuals.

**Comment by BobTheKerbal** [comment]
Ok. I will do so.

**Comment by BobTheKerbal** [comment]
Alright, starting to retry it one more time. I updated kopernicus to backport 1.3.1-13 and KSP to 1.3.1

**Comment by BobTheKerbal** [comment]
Loading bar stuck on "Module Manager" and the screen says Status for some reason and inbetween pictures it goes black and the debug menu is a sea of red.

**Comment by BobTheKerbal** [comment]
Also, My logs is from a different time I had ksp, then I re downloaded it, so the logs won't really help.

**Comment by TheProtagonists** [comment]
Can I see an image of the inside of your GameData folder?
I would suggest you to just get a completely fresh install and add mods from the ground up.

**Comment by BobTheKerbal** [comment]
How do I send a print screen picture, I don't use Gyazo,...

**Comment by TheProtagonists** [comment]
Just upload it to imgur or anywhere and send me a link

**Comment by BobTheKerbal** [comment]
https://imgur.com/CdRdO7f

**Comment by TheProtagonists** [comment]
Well... I don't even see a TheWorldBeyond folder there, but...
I'm afraid this is a mess. You have 2 scatterer folders, 2 module managers, 2 Kopernicus folders and a 1.5.1-1 for your 1.3.1 install, and almost all the star system mods you have are duplicated and not extracted correctly. There is even PlanetFactory, which is (extremely) outdated and conflicts with Kopernicus.
I strongly recommend you to just back up all that (just in case), delete everything and make a fresh new KSP install.

**Comment by BobTheKerbal** [comment]
I turned off the world beyond folder earlier because it kept not only not working, but crashing my game.
 and I am aware of the mess, I will clean it up right now.

**Comment by BobTheKerbal** [comment]
and I'm a young kid myself, so I would not expect amazing greatness of extracting mods well.

**Comment by BobTheKerbal** [comment]
_I don't think I really need a fresh slate of KSP, I really think all I need is to clean everything up, and retry._

**Comment by TheProtagonists** [comment]
I seriously doubt you will be able to load the game at all even without TWB or any planet mods.
Back up those mods to another place and just delete everything besides Squad. This will save you A LOT of time and frustration.

**Comment by BobTheKerbal** [comment]
Alright, I put my mods into the download folder. Now what?

**Comment by BobTheKerbal** [comment]
somehow the mod pack works!
somehow?

**Comment by BobTheKerbal** [comment]
I somehow got it to work.. oof
