### ISSUE TITLE
RemoteTech patches for the antenna parts

### ISSUE THREAD

**Issue by Gordon-Dry** [TheProtagonists/TheWorldBeyond#4]
The three antenna parts have no dedicated RemoteTech patches.

**Comment by Gordon-Dry** [comment]
I don't clone this to my local Github because - it's huge.

**Comment by Gordon-Dry** [comment]
I'm working on patches ...

**Comment by Gordon-Dry** [comment]
I suggest this one:
GameData\TheWorldBeyond\Parts\RemoteTech_patch.cfg
```
// RemoteTech patches provided by Gordon Dry

@PART[TWB-VeryBigAntenna-25-1]:NEEDS[RemoteTech]
{
	%MODULE[ModuleRTAntenna]
	{
		%Mode0DishRange = 0
		%Mode1DishRange = 10000000000000
		%EnergyCost = 24
		%MaxQ = 1000
		%DishAngle = 0.001
		
		%DeployFxModules = 1
		%ProgressFxModules = 1
		
		%TRANSMITTER
		{
			%PacketInterval = 0.1
			%PacketSize = 12
			%PacketResourceCost = 50.0
		}
	}
	%MODULE[ModuleSPUPassive] {}
}

@PART[TWB-VeryBigAntenna-25-2]:NEEDS[RemoteTech]
{
	%MODULE[ModuleRTAntenna]
	{
		%Mode0DishRange = 0
		%Mode1DishRange = 100000000000000
		%EnergyCost = 32
		%MaxQ = 750
		%DishAngle = 0.001
		
		%DeployFxModules = 1
		%ProgressFxModules = 1
		
		%TRANSMITTER
		{
			%PacketInterval = 0.1
			%PacketSize = 24
			%PacketResourceCost = 75.0
		}
	}
	%MODULE[ModuleSPUPassive] {}
}

@PART[TWB-VeryBigAntenna-25-X]:NEEDS[RemoteTech]
{
	%MODULE[ModuleRTAntenna]
	{
		%IsRTActive = true
		%Mode0DishRange = 0
		%Mode1DishRange = 2500000000000000
		%EnergyCost = 32
		%MaxQ = 250
		%DishAngle = 0.001
		
		%DeployFxModules = 1
		%ProgressFxModules = 1
		
		%TRANSMITTER
		{
			%PacketInterval = 0.1
			%PacketSize = 32
			%PacketResourceCost = 100.0
		}
	}
	%MODULE[ModuleSPUPassive] {}
}
```
I have to admit that I have to test it - especially for the
```
		%DeployFxModules = 1
		%ProgressFxModules = 1

```

**Comment by Gordon-Dry** [comment]
I changed :AFTER into :FOR - for reasons ...

**Comment by Gordon-Dry** [comment]
^ Changes - DishAngle = 0.001 for all antennas because in VAB lower values are rounded to 0.001 or even show 0.000

**Comment by Gordon-Dry** [comment]
btw the TWB-VeryBigAntenna-25-X got some wird animation issues in VAB.
- rotate works
- pivot works

^both a little quirky

- deploy (activate that thing) makes it jiggle like crazy.

**Comment by theonegalen** [comment]
Don't ever use :FOR unless it's :FOR the mod you're putting the config in.

Using :FOR[RemoteTech] in this config will tell module manager that Remote Tech is installed, even if Remote Tech is not installed. That means any patch that uses :NEEDS[RemoteTech] will activate, messing up the game for anyone who doesn't use Remote Tech.

**Comment by TheProtagonists** [comment]
The :FOR[RemoteTech] seems redundant and can cause problems. :NEEDS[RemoteTech] is sufficient.

**Comment by Gordon-Dry** [comment]
^ Edited.

**Comment by TheProtagonists** [comment]
I'll be adding the config you provided. Are you OK with the license of the mod of which this config will be under?

**Comment by Gordon-Dry** [comment]
This is just some config - I don't give a f about a license.

So take it and use it.

**Comment by TheProtagonists** [comment]
Added. Thanks!
