### ISSUE TITLE
Many "NullReferenceException: Object reference not set to an instance of an object"

### ISSUE THREAD

**Issue by Arrowstar** [TheProtagonists/TheWorldBeyond#5]
I created a clean install of KSP v1.5.1, and then placed the latest Koperincus, Community Terrain Texture Pack, EVE, and scatterer mods into my GameData folder.  I then downloaded the TWB_Full pack and placed the "TheWorldBeyond" folder in GameData.

When I start KSP and start a new game, it looks like KSP never loads anything.   I'm stuck at the black screen with the "loading" animation in the corner.

The KSP.log file is full of this message:

[EXC 19:52:55.011] NullReferenceException: Object reference not set to an instance of an object
	GalaxyCubeControl.Update ()

I have included my KSP.log file here for your review.  [KSPLog.zip](https://github.com/TheProtagonists/TheWorldBeyond/files/2592455/KSPLog.zip)

**Comment by TheProtagonists** [comment]
May I see a screenshot of your GameData folder?

**Comment by Arrowstar** [comment]
I had Kopernicus in the wrong place... everything works now. :)
